### ISSUE TITLE
Incorrect reference in the Risk Management Policy

### ISSUE THREAD

**Issue by blakeblackshear** [catalyzeio/policies#10]
Number 5 of the Risk Management Policy states,
> All Catalyze workforce members are expected to fully cooperate with all persons charged with doing risk management work, including contractors and audit personnel. Any workforce member that violates this policy will be subject to disciplinary action based on the severity of the violation according to Catalyze’s policies, which is outlined in the **Catalyze Policy Management Policy**.

However, I don't see any reference to disciplinary actions or severity of violations in the **Catalyze Policy Management Policy**.

I may be misinterpreting what is being outlined.

**Comment by travisjgood** [comment]
Good catch. This is an incorrect reference. Policy is updated to fix.
