### ISSUE TITLE
GitHub vs GitLab contradiction

### ISSUE THREAD

**Issue by blakeblackshear** [catalyzeio/policies#11]
In your **Approved Tools Policy**, you mention:
> **Gitlab.** Gitlab is an open source tool built on top of Git, the version control platform. Gitlab is hosted and secured by Catalyze. It is utilized for storage of configuration scripts and other infrastructure automation tools, as well as for source and version control of application code used by Catalyze.

However, in your **Configuration Management Policy**, you seem to reference Github:
> All committed code is reviewed using pull requests (on Github) to assure software code quality and proactively detect potential security issues in development.

Were you not able to meet some requirements around controls within Github and needed to switch to Gitlab?

**Comment by molsches** [comment]
We use both Gitlab and GitHub at Catalyze. We don't check sensitive information into GitHub, so if we have something that contains sensitive information and also requires Version Control, it is stored in Gitlab. So, the policies are accurate. Thanks for submitting the issue!
