### ISSUE TITLE
Appendices referenced in Incident Reporting Policy

### ISSUE THREAD

**Issue by sfreedman1** [catalyzeio/policies#14]
There are several places in the Incident Reporting Policy that reference appendices that seem to be referring to SANS documents. Where can we find these appendices? Thanks!

**Comment by travisjgood** [comment]
Yes, the appendices are SANS document templates. We'll get them added and the links live.

**Comment by sfreedman1** [comment]
thanks!

*Scott Freedman*
Chief Operating Officer, Epion Health <http://www.epionhealth.com>
Cell: 617-816-1973
sfreedman@epionhealth.com

**Comment by mradamcole** [comment]
Think you got the wrong person.

**Comment by molsches** [comment]
This was updated in a recent version of the docs. All related files are now included in the `source` folder of the project. Thanks for submitting an issue!
