### ISSUE TITLE
2 HITRUST Standards need to be moved from the Incident Response Policy to the Roles Policy

### ISSUE THREAD

**Issue by sfreedman1** [catalyzeio/policies#15]
There are two Applicable Standards from the HITRUST Common Security Framework that are listed in the Incident Response Policy but actually addressed in the Roles Policy. We are moving the reference to  following two standards from the Incident Response Policy to the Roles Policy to be consistent with the content covered in each of the two policies.

* 02.f - Disciplinary Process
* 06.f - Prevention of Misuse of Information Assets

**Comment by travisjgood** [comment]
Moved. Thanks for the correction
