### ISSUE TITLE
A Typo in System Access Policy Document

### ISSUE THREAD

**Issue by 0x4D31** [catalyzeio/policies#17]
In "Access Establishment and Modification" section, in forth item, I think "commiserate" should be changed to "commensurate". 

> All access to Catalyze systems and services are reviewed and updated on an bi-annual basis to assure proper authorizations are in place **commiserate** with job functions. The form used to conduct account review is here.

**Comment by adamleko** [comment]
You are correct, this has been fixed. Thanks!
