### ISSUE TITLE
in Readme.md Data Recover Policy  --> Data Recovery Policy

### ISSUE THREAD

**Issue by mnimmny** [catalyzeio/policies#22]
![image](https://cloud.githubusercontent.com/assets/5152156/17305595/f9d1d990-57df-11e6-8301-f99721744055.png)

**Comment by molsches** [comment]
Good catch. I'll update this right now.

**Comment by molsches** [comment]
Fixed in https://github.com/catalyzeio/policies/commit/87bbc5c1005ec24bf49b43d400834ef908fa7442
