### ISSUE TITLE
Incident Response Policy - Duplicate HITRUST Mapping

### ISSUE THREAD

**Issue by NoahJaehnert** [catalyzeio/policies#25]
Hi there,

Small tweak, but wanted to let you know that in the ["Applicable Standards from the HITRUST Common Security Framework" section of the Incident Response Policy](https://github.com/catalyzeio/policies/blob/master/source/sections/incident_response_policy.md#applicable-standards-from-the-hitrust-common-security-framework), you list "11.a - Reporting Information Security Events" twice!

**Comment by molsches** [comment]
Thanks for finding that! I fixed the issue in https://github.com/catalyzeio/policies/commit/7ac2c3e64e609a965e9a3ef9cc754f76f4b70c73

**Comment by molsches** [comment]
Also, in the future don't hesitate to fork and pull request a fix! We were a bit slow over the holidays, but we welcome contributors to our policies. Definitely for typos, but also for things that you are seeing out in the field. We update the docs after our annual set of HITRUST audits or when we add new functionality to meet individual hospital needs, but we're happy to include the things other folks are seeing in the main policies too.
